package com.verto.app.feature.payment.application

/** Stable business diagnostics for payment validation and allocation failures. */
internal object PaymentFailureCodes {
    const val AMOUNT_INVALID = "PAYMENT_AMOUNT_INVALID"
    const val INVOICE_VOIDED = "PAYMENT_INVOICE_VOIDED"
    const val INVOICE_CURRENCY_UNKNOWN = "PAYMENT_INVOICE_CURRENCY_UNKNOWN"
    const val INVOICE_CURRENCY_INCOMPLETE = "PAYMENT_INVOICE_CURRENCY_INCOMPLETE"
    const val PAYMENT_CURRENCY_UNSUPPORTED = "PAYMENT_CURRENCY_UNSUPPORTED"
    const val INVOICE_EXCHANGE_RATE_REQUIRED = "PAYMENT_INVOICE_EXCHANGE_RATE_REQUIRED"
    const val INVOICE_EXCHANGE_RATE_INVALID = "PAYMENT_INVOICE_EXCHANGE_RATE_INVALID"
    const val EXCHANGE_RATE_REQUIRED = "PAYMENT_EXCHANGE_RATE_REQUIRED"
    const val EXCHANGE_RATE_INVALID = "PAYMENT_EXCHANGE_RATE_INVALID"
    const val CASH_AMOUNT_RATE_MISMATCH = "PAYMENT_CASH_AMOUNT_RATE_MISMATCH"
    const val EXCEEDS_REMAINING = "PAYMENT_EXCEEDS_REMAINING"
    const val DUPLICATE = "PAYMENT_DUPLICATE"
}
