package com.verto.app.core.error

/** Stable authentication diagnostics consumed by the canonical error pipeline. */
object AuthErrorCodes {
    const val FORM_INCOMPLETE = "AUTH_FORM_INCOMPLETE"
    const val VERIFY_INVITE_FIRST = "AUTH_VERIFY_INVITE_FIRST"
    const val RECOVERY_EMAIL_REQUIRED = "AUTH_RECOVERY_EMAIL_REQUIRED"
    const val OTP_FORMAT = "AUTH_OTP_FORMAT"
    const val INVALID_OTP = "AUTH_INVALID_OTP"
    const val EXPIRED_OTP = "AUTH_EXPIRED_OTP"
    const val PASSWORD_TOO_SHORT = "AUTH_PASSWORD_TOO_SHORT"
    const val PASSWORD_MISMATCH = "AUTH_PASSWORD_MISMATCH"
    const val INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    const val EMAIL_NOT_CONFIRMED = "AUTH_EMAIL_NOT_CONFIRMED"
    const val ALREADY_REGISTERED = "AUTH_ALREADY_REGISTERED"
    const val INVITE_USED = "AUTH_INVITE_USED"
    const val INVALID_INVITE = "AUTH_INVALID_INVITE"
    const val ACCOUNT_BLOCKED = "AUTH_ACCOUNT_BLOCKED"
    const val PROFILE_MISSING = "AUTH_PROFILE_MISSING"
    const val MEMBERSHIP_INVALID = "AUTH_MEMBERSHIP_INVALID"
    const val PROVISIONING_INCOMPLETE = "AUTH_PROVISIONING_INCOMPLETE"
    const val RECOVERY_SESSION_REQUIRED = "AUTH_RECOVERY_SESSION_REQUIRED"
    const val RECOVERY_VERIFICATION_UNAVAILABLE = "AUTH_RECOVERY_VERIFICATION_UNAVAILABLE"
}
